[supervisord]
nodaemon=true
user=root

[program:mariadb]
command=mariadbd --user=mysql --skip-networking=0 --bind-address=0.0.0.0 --port=3306
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:orangehrm]
command=catalina.sh run
directory=/opt/tomcat
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=JAVA_OPTS="-Dcatalina.base=/opt/tomcat -Dcatalina.home=/opt/tomcat -Djava.io.tmpdir=/opt/tomcat/temp"